### ISSUE TITLE
Segger System View support on different platforms setup documentation.

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [apache/incubator-nuttx#5843]
I've noticed this PR https://github.com/apache/incubator-nuttx/pull/5327 and tried to get Segger System View it on my S32K144 based board.

Unfortunely there wasn't a how to guide, but I tried to mimick the SIM sysview configuration https://github.com/anchao/incubator-nuttx/blob/9efb473feaa116b61c6d47d00878baf6a08a167d/boards/sim/sim/sim/configs/sysview/defconfig

When compiling though I got a couple of errors:

1. Regarding a ASM file optimized for ARMv7 `SEGGER_RTT_ASM_ARMv7M.S`, my workaround was to remove that from build system and use the fallback C file.

2. Some errors regarding missing `up_perf_gettime` and `up_perf_getfreq` function, I circumvented this by enabling CONFIG_TIMER_ARCH which implements these functions, but it seems that the sim config didn't require those.

After this it successfully compiles and it seems I can connect through SEGGER systemview,
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/57130844/160156326-e7a2c16a-63be-46d4-bee7-f2ce54339bea.png)

However as you can see it's partly working however time stays at zero and I can't see task switching itself.

@anchao would you be able to provide steps you did to get it to work on your Cortex-M55 platform, or do you have an idea on which interfaces I need implement/enable to get this fully to work?

**Comment by anchao** [comment]
Hi @PetervdPerk-NXP  ,

> Unfortunely there wasn't a how to guide, but I tried to mimick the SIM sysview configuration

Yes, the SIM configuration simply enables the configuration to ensure that the compilation can work normally. 

We will add a back-end based on file to save the system view stream on SIM platform, which is still under development

> Regarding a ASM file optimized for ARMv7 SEGGER_RTT_ASM_ARMv7M.S, my workaround was to remove that from build system and use the fallback C file.

Sorry to confuse you, I just tested the configuration under v8m, you can temporarily remove the optimization of v7m, I will try to fix this issue further 

> Some errors regarding missing up_perf_gettime and up_perf_getfreq function, I circumvented this by enabling CONFIG_TIMER_ARCH which implements these functions, but it seems that the sim config didn't require those.

I have uploaded a new PR, they implemented cycle counter based on DWT, you can try this commit:

https://github.com/apache/incubator-nuttx/pull/5850

In addition, you also need to initialize the CPU clock frequency in the board implement, eg:

https://github.com/apache/incubator-nuttx/pull/5850/commits/b5edd67cc592a226c9b0fe32914ac5763c78eea9#diff-2e2c7b8e12a8db8218fd22d16f664621da802957420e528caf0c44d0307dc819R57

> do you have an idea on which interfaces I need implement/enable to get this fully to work?

I think this should be caused by the cycle counter not working properly, please check whether up_perf_init() or up_perf_gettime() is working properly

**Comment by PetervdPerk-NXP** [comment]
Hi @anchao ,

We've rebased on #5850 and implemented the up_perf_init() hook on our board and it seems to be working fine now.

Would it be something to include some documentation on how to use Segger Systemview in the official NuttX documentation?
https://nuttx.apache.org/docs/latest/

**Comment by xiaoxiang781216** [comment]
We are planning to invite the professional technical writer to improve the document, please stay tuned.

**Comment by xiaoxiang781216** [comment]
> When compiling though I got a couple of errors:
> 
> 1. Regarding a ASM file optimized for ARMv7 `SEGGER_RTT_ASM_ARMv7M.S`, my workaround was to remove that from build system and use the fallback C file.

@PetervdPerk-NXP https://github.com/apache/incubator-nuttx/pull/5930 could fix the above issue.
